### ISSUE TITLE
Problema no Main

### ISSUE THREAD

**Issue by HenriqueCarrara0** [DisciplinasProgramacao/poo_tp_manha-thwh#3]
@joaocaram 

Bom dia professor, estamos com um problema no "autenticar" do "App", onde o mesmo fica apresentando erro no editor de código-fonte. Tentamos trocar o nome, mas continua dando o problema.

-Versão com erro(executamos alguns testes)
// Autenticando um espectador
            Autenticador autenticador = new Autenticador();
            autenticador.criarEspectador("usuario3", "senha789", "Pedro");
            boolean autenticado = autenticador.autenticarEspectador("usuario3", "senha789");
            System.out.println("Espectador autenticado: " + autenticado);

-Versão "melhorada", que ainda apresenta erros(fica marcado como incorreto no Editor de código-fonte)
// Autenticando um espectador
            Autenticador espectador = new Autenticador();
            autenticador.criarEspectador();
            boolean autenticado = autenticador.autenticarEspectador("usuario3", "senha789");
            System.out.println("Espectador autenticado: " + autenticado);

**Comment by joaocaram** [comment]
@HenriqueCarrara0 , você está criando uma variável com um nome (espectador)  e tentando usar com outro (autenticador)

```
Autenticador espectador = new Autenticador();
autenticador.criarEspectador();
```
