### ISSUE TITLE
Problema no arquivo

### ISSUE THREAD

**Issue by HenriqueCarrara0** [DisciplinasProgramacao/poo_tp_manha-thwh#4]
@joaocaram 
Prezado, professor Caram!
Estamos com os mesmo problemas no arquivo que foi mostrado durante a apresentação de hoje. Gostaríamos que o senhor nos ajude a encontrar os erros e o que deve ser modificado, pois não sabemos o que fazer. Pode ser um erro bobo, mas não estamos identificando o erro, já que testamos de tudo ao nosso alcance e conhecimento. Além disso,  nosso grupo(Eu e Thiago) consta com metade dos participantes executando as diferentes e complicadas tarefas, sendo muito complicado conciliar com as outras matérias. Por isso, que precisamos do seu auxílio nesse problema.
Att Henrique e Thiago.

**Comment by joaocaram** [comment]
@HenriqueCarrara0 @DisciplinasProgramacao/thwh Pessoal, se for o erro nos arquivos a gente já sabe o erro desde ontem: é porque vocês mexeram no lugar onde os arquivos de dados. O que eu sugiro é voltar para a versão de antes de terem feito esta mudança, já que estava funcionando. Esta tarefa era lá do começo do trabalho, ou seja, a quantidade de integrantes não tem ou teve muito impacto nisso. Só posso olhar mais detalhadamente quando terminar as correções de todas as notas.
